version: "3.8"

services:
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - "./src:/opt:rw"
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    depends_on:
      - db

  db:
    container_name: "db"
    hostname: "db"
    image: postgres:16-alpine3.19
    env_file:
      - ".env"
    volumes:
      - ./data:/var/lib/postgresql/data
