# Generated by Django 5.0.4 on 2024-04-08 18:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='категория')),
                ('slug', models.SlugField(allow_unicode=True, db_index=False, help_text='URL категории', max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='URL')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок статьи', max_length=128, validators=[django.core.validators.MinLengthValidator(limit_value=5)], verbose_name='заголовок')),
                ('slug', models.SlugField(allow_unicode=True, db_index=False, help_text='URL статьи', max_length=128, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=5)], verbose_name='URL')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', related_query_name='article', to='blog.category')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ['-date_created'],
            },
        ),
    ]
